### PR TITLE
update for swift 4.1

### PR DESCRIPTION
**Pull request by edwardvalentini**
just updating `make-pkgconfig.swift` to use `compactMap` instead of `flapMap` for swift 4.1

### CODE REVIEW

**Comment by harlanhaskins** [comment]
Thank you! Until Travis CI supports Xcode 9.3,

**Comment by harlanhaskins** [comment]
Oops, please ignore. Sorry, got half way through a comment and hit the wrong button.

**Comment by CodaFi** [comment]
Hello, thank you for the change.

In order to land this, you'll need to update the Travis build script to point at Swift 4.1.  Before you do that, I have a request: #95 is where we disabled the Linux build because of an unfortunate oversight in the build script.  If you could, let me know if you'd be willing to look into re-enabling that build configuration for 4.1.  It's entirely optional, but it would be a huge help if you could.

**Comment by edwardvalentini** [comment]
sure i can definitely take a look at the travis build script.

**Comment by CodaFi** [comment]
Holy cow, that worked like a charm. ✨ 

Thank you so very very much.  I'm going to release this as a new version of LLVMSwift.

⛵️

**Pull request merged**
