### PR TITLE
Add Linux to the Build Matrix

### PR DESCRIPTION
**Pull request by CodaFi**

### CODE REVIEW

**Comment by harlanhaskins** [comment]
We should just set

```
PKG_CONFIG_PATH=$(pwd):$(PKG_CONFIG_PATH)
```

And call it a day.

**Comment by CodaFi** [comment]
I'm out of ideas.  Can you talk to Ankit about this?

**Comment by CodaFi** [comment]
Looks like `Process` was still called `Task` when this snapshot was put out.

**Comment by harlanhaskins** [comment]
Try 3.0.2?

**Comment by CodaFi** [comment]
Gonna fold these commits after seeing what happens.  The first has 3.0 snapshot and uses `Task`, the second has 3.0.2 snapshot and uses `Process`.

**Comment by CodaFi** [comment]
No dice.

**Comment by harlanhaskins** [comment]
Well, won't that fail on macOS? What about

```swift
#if os(Linux)
typealias Process = Task
#endif
```

**Comment by CodaFi** [comment]
@harlanhaskins I'm happy with this.  Review please!

**Comment by harlanhaskins** [comment]
Yay!

**Pull request merged**
