### PR TITLE
Support for LLVM 11

### PR DESCRIPTION
**Pull request by twof**
I've also pegged LLVM at 11 in the readme and bumped the minor version in the SPM installation instructions. Let me know if there are any tests or CI I should run 😄

### CODE REVIEW

**Comment by twof** [comment]
Resolves #218 and I'll be able to close #219 if you decide to merge this.

**Review by segiddins — APPROVED** [review]

**Comment by segiddins** [comment]
Hey, thanks for the PR! There’s one last thing we need: utils/make-pkgconfig needs its version numbers bumped.

**Comment by twof** [comment]
@segiddins I think that about does it. Let me know if anything else needs doing!

**Comment by alexanderuv** [comment]
Looking forward for this change!! 👍🏼

**Pull request merged**
