### PR TITLE
Update to LLVM 9.0

### LINKED ISSUE #215: Does not compile under LLVM 9
LLVMSwift won't compile under LLVM 9. Some of LLVMSwift's LLVM-C API extensions appear to have been upstreamed, causing errors such as the following:

```
llvmshims/src/shim.cpp:43:5: redefinition of enumerator 'LLVMBinaryTypeArchive'
    LLVMBinaryTypeArchive,
    ^
llvmshims/src/shim.cpp:44:5: redefinition of enumerator 'LLVMBinaryTypeMachOUniversalBinary'
    LLVMBinaryTypeMachOUniversalBinary,
  ^
# etc.
```

I'm not sure what the protocol is for adopting upstream versions of these API. i.e., do older LLVM versions still have to be supported? If so, should that be done with version macros, or otherwise?

(btw, this package has been excellent to me, thank you for maintaining it!)

### PR DESCRIPTION
**Pull request by dduan**
Closes #215

### CODE REVIEW

**Comment by dduan** [comment]
need to figure out what's different in the Ubuntu releases. Currently the logic for finding llvm-c's header is failing.

**Comment by Azoy** [comment]
Any update on this? No rush, but just curious.

**Comment by dduan** [comment]
I'm attempting to migrate CI to either a later release of Ubuntu LTS or Swift.

**Comment by matthewseaman** [comment]
@dduan I assume this doesn't cover LLVM 10. Are there other forks that are still being maintained?

**Pull request merged**
