### PR TITLE
Diagnostics, 4Real This Time

### PR DESCRIPTION
**Pull request by CodaFi**

### CODE REVIEW

**Review by harlanhaskins — APPROVED** [review]

**Comment by harlanhaskins** [comment]
:shipit:

**Comment by CodaFi** [comment]
Still needs carets and pretty colors

**Comment by harlanhaskins** [comment]
Trill has an `ANSIColorStream`...

**Comment by CodaFi** [comment]
One day, when we have test dependencies

**Comment by CodaFi** [comment]
⛵️

**Pull request merged**
